const SpecialtiesData = [
  "Restructuring",
  "Coronial",
  "NFTs",
  "Mediations",
  "Planning & Environment",
  "Construction",
  "Consumer Law",
  "Virtual Courts",
  "Fintech",
  "Capital Markets",
  "Alternative Dispute Resolution",
  "Commercial",
  "Traffic Law",
  "Internet",
  "Liquidations",
  "Debt Recovery",
  "Insurance",
  "Human Rights",
  "Public Law",
  "Clubs & Associations",
  "Social Welfare Law",
  "Civil Procedure",
  "General",
  "Company Secretarial",
  "Trust Setup & Admin",
  "Media",
  "Credit",
  "Costs",
  "Specialist Advocate",
  "Real Property",
  "Subpoenas",
  "Intellectual Property",
  "Competition Law",
  "Regulatory Investigations",
  "Charities & Not for Profits",
  "Occupational Regulation",
  "Arbitration",
  "Administrative Law",
  "Resources & JORC",
  "Defence",
  "Crypto",
  "Blockchain",
  "Wills & Estates",
  "Cyber Law",
  "Crime",
  "Startups",
  "Privacy & Data",
  "Legaltech",
  "Animal Law",
  "Defamation",
  "Debt Collection",
  "Admiralty Law",
  "Transport",
  "Derivatives",
  "Compensation",
  "Islamic Law",
  "Aviation Law",
  "Appellate",
  "Funds Management",
  "Technology",
  "Construction",
  "Banking & Finance",
  "Securities",
  "Tax",
  "Financial Services",
  "Church Law",
  "Class Actions",
  "Natural Resources",
  "Industrial Law",
  "Employment",
  "Free Legal Services",
  "Insolvency",
  "Tax Controversy",
  "Regtech",
  "Space Law",
  "Family Law",
  "Workplace Relations",
  "Drone Law",
  "Franchising",
  "LGBTI",
  "International Law",
  "Mergers & Acquisitions",
  "Immigration Law",
  "Prosecution",
  "Personal Injury",
  "Artificial Intelligence",
  "Equity",
  "Discrimination",
  "Corporations",
  "Institutional Abuse",
  "Native Title",
  "Medical Negligence",
];


export default SpecialtiesData;